// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for creating a new user.
 */
export type CreateUserRequest = {
  /**
   * User email address.
   */
  email: string;
  /**
   * Display name.
   */
  name: string;
};
