// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for updating an existing user.
 */
export type UpdateUserRequest = {
  /**
   * Updated email address (optional).
   */
  email: string | null;
  /**
   * Updated display name (optional).
   */
  name: string | null;
};
