// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Serialisable user representation returned by the API.
 */
export type UserResponse = {
  id: string;
  email: string;
  name: string;
  created_at: string;
  updated_at: string;
};
