// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Core User domain entity.
 *
 * This struct represents a user in the system and is the single source of truth
 * for the user's shape. Thanks to `ts-rs`, a matching TypeScript interface will
 * be generated automatically.
 */
export type User = {
  id: string;
  email: string;
  name: string;
  created_at: string;
  updated_at: string;
};
